version: "3.8"
services:
    backend:
    
        build: 
        # We use the dockerfile file in the following path : 
          context: "./backend_api_multitask"
        networks: 
          - devops-network
        ports:
          - "8980:8080"
        depends_on: 
          - database

    database:
        build: 
        # We use the dockerfile file in the following path : 
          context: "./postgres"
        networks: 
          - devops-network
        ports:
          - "5432:5432"
        environment:
          POSTGRES_PASSWORD: we4reDATA

    httpd:
        build: 
        # We use the dockerfile file in the following path : 
          context: "./backend_api_multitask/src/main/HTTP"
        ports:
          - "8082:80"
        networks: 
          - devops-network
        depends_on:
          - backend
        

networks:
  devops-network:

volumes:
  postgres_volume:
